### ISSUE TITLE
Contribute page 

### ISSUE THREAD

**Issue by mehulkar** [TeaWithStrangers/making-tws#3]
On making website, the contribute page points to `/github`, 

but the README on TWS main repo now points to `/contribute`.

~~Neither exist.~~ Both 404.

1. https://github.com/TeaWithStrangers/making-tws/blob/master/source/partials/_header.haml#L9
2. https://github.com/TeaWithStrangers/tws-on-rails/commit/aa07a721e05ba5b72f2d06e3e0c47b6129e4d296

**Comment by nickbarnwell** [comment]
I `git push`'d in the wrong repo :( Working on making it a non-issue. Watch this space :)

**Comment by nickbarnwell** [comment]
Closed by #2!.
