### ISSUE TITLE
Add yourself to the Team page

### ISSUE THREAD

**Issue by nickbarnwell** [TeaWithStrangers/making-tws#4]
We give everyone who submits a pull request or fix to Tea With Strangers a spot on our [Team Page](http://making.teawithstrangers.com/team/). If you'd like to be included, please add the relevant information in `data/team.yml`! If you'd prefer to remain unfeatured, just mark the issue as closed.

Thanks again!
Nick & The TWS Crew

**Comment by clwrightwhen** [comment]
Hey @nickbarnwell - quick question! Would I follow the same procedure as creating a git branch, doing a pull request, etc. as before?
Thanks!

**Comment by nickbarnwell** [comment]
Yup! You’ll also need to add an image – please make sure it’s square and at least 256x256.

Let me know if you have any more questions.
