### ISSUE TITLE
Github link is broken 

### ISSUE THREAD

**Issue by yrizk** [TeaWithStrangers/making-tws#6]
someone mentioned in the HN post. its true :( 
simple fix, im on it.

**Comment by nickbarnwell** [comment]
It was already fixed!

**Comment by nickbarnwell** [comment]
But thanks for opening. I killed everything that should be a redirect since we're hosting statically for now.

**Comment by yrizk** [comment]
are we talking about the same thing? http://making.teawithstrangers.com/ still links to https://github.com/teawithstrangers.com

**Comment by nickbarnwell** [comment]
Ha, originally it was pointing to /github and I changed it to gh/teawithstrangers but typed the .com out of muscle memory. Fixed and deployed, thanks for catching my mistaken fix!

**Comment by nickbarnwell** [comment]
Fixed by c833b9e36e50ecf9cee70842518227d72603585c
